language: go

go:
  - 1.7.x
  - 1.8.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)